### ISSUE TITLE
ZeroDivisionError - constants.py

### ISSUE THREAD

**Issue by amrosado** [SecurityInnovation/PGPy#157]
When forming a new public and private key together with a subkey and then password protecting the key like this:

```
key = pgpy.PGPKey.new(PubKeyAlgorithm.RSAEncryptOrSign, 4096)
pw = 'd71ien2318138kk3'

key.protect(pw, SymetricKeyAlgorithm.AES256, HashAlgorithim.SHA256)
```

Gives the ZeroDivisionError:

> line 354, in tune_count
>     ct = int(len(_hashtunedata) * (_TIME / (end - start)))
> ZeroDivisionError: float division by zero

I believe this is because not a significant amount of time has occurred between the start and end time used in tune_count.  When I looked closer at the tune_count it looks like there was no difference in the start and end time on my system.  I attempted to change it into this:

```
start = time.time()
h = self.hasher
h.update(_hashtunedata)
sysRnd = SystemRandom()
time.sleep(sysRnd.uniform(0.0000001, 0.0000002))
end = time.time()
```

I feel like this might be somewhat system dependent.  Sometimes I get the error and sometimes I don't.  I thought it might be better to have somewhat a variable time based on SystemRandom to add some entropy into the process.

**Comment by Commod0re** [comment]
Thanks for submitting this bug report! I'll be taking a look at improving this one today.

The purpose of the count (which comes from the OpenPGP RFC) is to have the hashing process for turning your passphrase into the symmetric key that is used to protect/unprotect your private key take some time so that cracking that passphrase takes longer, and to allow the amount of time taken to be tunable so it can try to keep up with computers as they get faster. (Bearing in mind that I don't actually think that the method used for the current OpenPGP String2Key is very good, but that's what we have to work with)

The unfortunate thing about the count is that very fine adjustments disappear because of the way it's stored in the String2Key specifier (being [expanded](https://tools.ietf.org/html/rfc4880#section-3.7.1.3) from an 8-bit unsigned integer to a 32-bit unsigned integer), very fine adjustments actually disappear when storing that count.

Given those two things, adding entropy to this process isn't actually going to help at all over just sleeping for a constant time (and sleeping too long might measurably decrease the amount of time taken to run the String2Key process, making your passphrase easier to crack if someone got ahold of your private key)

--

Anyway, the way I wrote that tune_count, it hashes 100 KiB, measures how long that takes, and tries to extrapolate from that measurement how many bytes would need to be hashed for it to take about 100ms. On your system, 100 KiB might not be enough to get a measurable time difference with SHA256 (maybe insufficient resolution in the time source, or your computer is very fast, or something else). At any rate, the robustness of that process could certainly be improved.

**Comment by amrosado** [comment]
Makes sense, I didn't think there would be much of a difference given that there was probably a small amount of time occurring during the process.  I believe my computer is fairly fast computationally so it makes sense that both from a computational time and resolution perspective.

Would you consider changing the amount of KiB being hashed in the tune_count? Should I just enter in a sleep time in this area?  I've attempted to use os.urandom(102,400) instead, but the computational time still overlaps.

**Comment by Commod0re** [comment]
I am planning, at least for a first try to improve this, to add some logic to that routine to have it hash more if needed, and see how that works out. I did have it hash more previously (I think it was 1 MiB, but that was noticeably slow on some machines I'd tried it on) so I reduced the amount to make it more "seamless" feeling in those cases.

I can think of a couple of possible workarounds:

1. Increase the size of _hashtunedata:

    ```python
    # this is 100 KiB
    _hashtunedata = bytearray([10, 11, 12, 13, 14, 15, 16, 17] * 128 * 100)
    ```

    change the 100 at the end to a larger number, and tune_count will account for the different size. I haven't tried monkey-patching it, but depending on how you do your imports you might even just be able to get away with something like:

    ```python
    import pgpy
    # use a suitably large amount of data for your machine 
    pgpy.constants._hashtunedata = bytearray(...)
    ```

2. Set _tuned_count manually for the HashAlgorithm you're using, e.g.:

    ```python
    import pgpy
    pgpy.constants.HashAlgorithm.SHA256._tuned_count = 255
    ```

**Comment by amrosado** [comment]
I see.  Yeah it makes sense that it could be a valuable measurement to have.  Maybe you can use a try and except statement in that part of the method?  In the exception case you can manually set the tuned_count or hash to a larger size of data.  It only fails periodically on my system.  It could be setup specifically to catch the ZeroDivisionException.  Given what you've said, I've just interjected a small amount of sleep time into to tune count.  Also, I think this could also be interesting using update more than once, but you need a indexable array to input into the hash function.

**Comment by Commod0re** [comment]
Catching exceptions is sort of expensive, so I think that maintaining a relatively accurate measurement would get complicated (it could easily produce excessively weak count values)

I've added some logic to check the time difference and hash more than once if the precision of time.time isnt enough to measure the difference. Based on testing that, I think it should reliably produce good values, at least until the maximum count value is no longer effective for current computers.
