### ISSUE TITLE
Is anyone aware of any security audits?

### ISSUE THREAD

**Issue by kevinl95** [SecurityInnovation/PGPy#242]
I found on the PGP mailing list that an internal security audit of PGP was done by Security Innovation when they released 0.3.0. Is this publicly accessible anywhere, or is anyone aware of somewhere I could access an audit done on this library? Thanks!

**Comment by evilaliv3** [comment]
@kevinl95, do you have any update on this?

Actually this would be very important for many projects. E.g. we are evaluating the adoption of PGPy in @Globaleaks

**Comment by kevinl95** [comment]
I'm afraid I never did hear back, and was unable to find any public third-party audits.

**Comment by evilaliv3** [comment]
Oo :/

**Comment by joebasirico** [comment]
Hi all, 

Joe here, SVP of Engineering at SI. First off I'm excited to see the interest in PGPy! Sorry for the slow response I was on vacation last week. 

Since we're a security company we did do a code review of this project ourselves, our assessment team is different from the team that wrote this code. However, I know that doesn't count as a 3rd party review. 

I'm not sure which release we did the review on, I'll try to dig it up when I get into the office next week.

Joe

**Comment by joebasirico** [comment]
Hi, 

I just wanted to close the loop on this request. I looked for this internal assessment report and it looks like it was either destroyed or moved to offline storage (the case for all of our assessment reports over 6 months old). Sorry I couldn't find it, but I would welcome an external 3rd party assessment, on this project, and we'd love to dedicate some resources to fixing any potential issues found.

If you're using or considering using PGPy please reach out to me or the original author, @Commod0re, for more information.

**Comment by kevinl95** [comment]
Thanks for looking into it!
