### ISSUE TITLE
Is this project still alive ?

### ISSUE THREAD

**Issue by AnatomicJC** [SecurityInnovation/PGPy#399]
Hi 👋 

I just wanted to know if this project was still active ? I tried to reach maintainers some months ago for some advice but got no reply 😕 

Cheers,

**Comment by dkg** [comment]
it's been pretty silent lately, which is a shame because it has been lagging on the [OpenPGP Interoperability tests](https://tests.sequoia-pgp.org/), and i think some amount of additional work could help improve it there.

I created `pgpy2` in an attempt to entertain a fork a while back, but i haven't had the capacity to push that forward.

**Comment by Commod0re** [comment]
I'm back
